# Generated by Django 5.2.6 on 2025-09-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='review_media/')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='polls.review')),
            ],
        ),
        migrations.CreateModel(
            name='WearTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wear_test', to='polls.review')),
            ],
        ),
    ]
