# Generated by Django 5.2.6 on 2025-09-14 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_review_receipt_reviewmedia_weartest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description'),
        ),
        migrations.AddField(
            model_name='review',
            name='age_range',
            field=models.CharField(blank=True, help_text='18-24, 25-34, 35-44, 45-54, 55+', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='skin_tone',
            field=models.CharField(blank=True, help_text='Fair, Light, Medium, Tan, Deep', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='skin_type',
            field=models.CharField(blank=True, help_text='Oily, Dry, Combination, Sensitive, Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='weartest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weartest',
            name='notes',
            field=models.TextField(blank=True, help_text='Wear test observations'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('lipstick', 'Lipstick'), ('mascara', 'Mascara'), ('eyeshadow', 'Eyeshadow'), ('concealer', 'Concealer'), ('blush', 'Blush'), ('highlighter', 'Highlighter'), ('skincare', 'Skincare'), ('powder', 'Powder')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='polls.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
